### ISSUE TITLE
how can i create a tracking page?

### ISSUE THREAD

**Issue by harryp-art** [ShipEngine/shipengine-php#32]
**Describe the bug**

I want to create brand tracking page in development, my api-key is TEST..........z and  this is my code:

```
let data = {
    "tracking_pages": [
      {
        "tracking_number": "890...",
        "carrier_code": "ups",
        "service_code": "ups",
      }
    ]

  };
      var options = {
        method: 'POST',
        url: 'https://api.shipengine.com/v-beta/tracking_page',
        headers: {
          Host: 'api.shipengine.com',
          'API-Key': 'TEST_a1b1c1...z',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      }
      request(options, function (error, response) {
        if (error) throw new Error(error)
        console.log(response.body)
      })

```
but it returns this error

{
    "request_id": "b3a5190c-1-4099-1-7151179be0d8",
    "errors": [
        {
            "error_source": "shipengine",
            "error_type": "security",
            "error_code": "unauthorized",
            "message": "An API key is required. Please see https://www.shipengine.com/docs/auth"
        }
    ]
}

**Comment by AnneOReilly** [comment]
Closing as duplicate
