### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by alexandrecruz** [ShipEngine/shipengine-php#34]
## Description

Hi ShipEngine team,

Could you please make the dependency `friendsofphp/php-cs-fixer` a dev dependency?
When I try to install its conflicting with the project but it should not be part of the non-dev dependencies.

Thanks

**Comment by sushithegreat** [comment]
Fixed in [#35](https://github.com/ShipEngine/shipengine-php/pull/35)
